-- MySQL Script generated by MySQL Workbench
-- Thu Jun 24 12:19:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database_book
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database_book
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_book` DEFAULT CHARACTER SET utf8 ;
USE `database_book` ;

-- -----------------------------------------------------
-- Table `database_book`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_book`.`genre` (
  `idgenre` INT NOT NULL AUTO_INCREMENT,
  `Genre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_book`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_book`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database_book`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database_book`.`Books` (
  `idBooks` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Genre` VARCHAR(45) NOT NULL,
  `Author` VARCHAR(45) NOT NULL,
  `DateCreate` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBooks`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
